In [211]:
import pandas as pd
import os
import numpy as np
import pandas as pd

In [212]:
    #Read the Population dataset from the CSV file.
    #● Use the pandas library.
    population = pd.read_csv('/content/population.csv')
    population_data = pd.DataFrame(population)
    #● Display the first five rows.
    population_data.head(5)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [213]:
#● Check the shape and data types.
population_data.shape

(25, 2)

In [214]:
print(type(population_data))

<class 'pandas.core.frame.DataFrame'>

In [215]:
#Read the GDP dataset from the Excel file.
gdp = pd.read_excel("/content/gdp.xlsx")
gdp_data = pd.DataFrame(gdp)
gdp_data.columns

Index(['Country', 'GDP'], dtype='object')

In [216]:
print(type(gdp_data))

<class 'pandas.core.frame.DataFrame'>

In [217]:
#Read the Internet Users dataset from the JSON file.
internet_users = pd.read_json('/content/internet_users.json')
internet_df = pd.DataFrame(internet_users)

In [218]:
#Read the Literacy Rate dataset from the XML file.
literacy_rate = pd.read_xml('/content/literacy_rate.xml')
literacy_df = pd.DataFrame(literacy_rate)

In [219]:
#Explore each dataset.
#● Number of rows
#● Number of columns
#● Column names
#● Data types
#● Missing values
#● Duplicate records
print(f" Number of rows: {len(population_data.index)}")
print(f" Number of columns: {len(population_data.columns)}")
print(f"Column Name: {population_data.columns.tolist()}")
print(f"Datatype: {type(population_data)}")
population_data.fillna(0)
population_data.drop_duplicates()

 Number of rows: 25
 Number of columns: 2
Column Name: ['country', 'population']
Datatype: <class 'pandas.core.frame.DataFrame'>

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [220]:
#Explore each dataset.
#● Number of rows
#● Number of columns
#● Column names
#● Data types
#● Missing values
#● Duplicate records
print(f" Number of rows: {len(gdp_data.index)}")
print(f" Number of columns: {len(gdp_data.columns)}")
print(f"Column Name: {gdp_data.columns.tolist()}")
print(f"Datatype: {type(gdp_data)}")
gdp_data.fillna(0)
gdp_data.drop_duplicates()

 Number of rows: 25
 Number of columns: 2
Column Name: ['Country', 'GDP']
Datatype: <class 'pandas.core.frame.DataFrame'>

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [221]:
#Explore each dataset.
#● Number of rows
#● Number of columns
#● Column names
#● Data types
#● Missing values
#● Duplicate records
print(f" Number of rows: {len(internet_df.index)}")
print(f" Number of columns: {len(internet_df.columns)}")
print(f"Column Name: {internet_df.columns.tolist()}")
print(f"Datatype: {type(internet_df)}")
internet_df.fillna(0)
internet_df.drop_duplicates()

 Number of rows: 25
 Number of columns: 2
Column Name: ['country', 'internet_users']
Datatype: <class 'pandas.core.frame.DataFrame'>

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [222]:
#Explore each dataset.
#● Number of rows
#● Number of columns
#● Column names
#● Data types
#● Missing values
#● Duplicate records
print(f" Number of rows: {len(literacy_df.index)}")
print(f" Number of columns: {len(literacy_df.columns)}")
print(f"Column Name: {literacy_df.columns.tolist()}")
print(f"Datatype: {type(literacy_df)}")
literacy_df.fillna(0)
literacy_df.drop_duplicates()

 Number of rows: 25
 Number of columns: 2
Column Name: ['name', 'literacy_rate']
Datatype: <class 'pandas.core.frame.DataFrame'>

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [223]:
#Rename columns wherever necessary so that all datasets have a common column  name for merging.
gdp_data.rename(columns={gdp_data.columns[0]:'country'},inplace=True)

In [224]:
#Rename columns wherever necessary so that all datasets have a common column  name for merging.
literacy_df.rename(columns={literacy_df.columns[0]:'country'},inplace=True)

In [225]:
#Convert the required columns into appropriate numeric data types.
population_data['population'] =pd.to_numeric(population_data['population'],errors='coerce')

In [226]:
#Convert the required columns into appropriate numeric data types.
gdp_data['GDP'] =pd.to_numeric(gdp_data['GDP'],errors='coerce')

In [227]:
#Convert the required columns into appropriate numeric data types.
internet_df['internet_users'] =pd.to_numeric(internet_df['internet_users'] ,errors='coerce')

In [228]:
literacy_df['literacy_rate']=pd.to_numeric(literacy_df['literacy_rate'],errors='coerce')

In [229]:
merged_1 = pd.merge(population_data, gdp_data, on='country', how='inner')
merged_2 = pd.merge(merged_1, internet_df, on='country', how='inner')
final_merge = pd.merge(merged_2, literacy_df, on='country', how='inner')
final_merge.head()

         country  population       GDP  internet_users  literacy_rate
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

In [230]:
#Create the following calculated columns:
#1. Internet Penetration (%)
#2. GDP Per Capita
final_merge['internet_penetration'] = final_merge['internet_users'] / population_data['population'] * 100
final_merge['internet_penetration'] = final_merge['internet_penetration'].round(2)
final_merge['gdp_per_capita'] = final_merge['GDP'] / final_merge['population']
final_merge['gdp_per_capita'] = final_merge['gdp_per_capita'].round(2)
final_merge.head()

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

In [231]:
conn = sqlite3.connect('country_statistics.db')
final_merge.to_sql('country_statistics', conn, if_exists='replace', index=False)

25

In [232]:
#Verify that the data has been loaded successfully.
verification = pd.read_sql_query("SELECT * FROM country_statistics LIMIT 5;", conn)
verification

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

In [233]:
top_gdp = final_merge.sort_values(by='gdp_per_capita', ascending=False).head(5)
top_gdp

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07

In [234]:
top_population = final_merge.sort_values(by='population', ascending=False).head(5)
top_population

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
15,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
10,Brazil,212559417,2330000,181000000,93.2,85.15,0.01

In [235]:
avg_literacy = final_merge['literacy_rate'].mean()
avg_literacy

np.float64(97.248)

In [236]:
final_merge[final_merge['literacy_rate']>90][['country', 'literacy_rate']]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [237]:
final_merge[final_merge['internet_penetration']>70][['country', 'internet_penetration']]

           country  internet_penetration
0    United States                 94.26
1            China                 76.50
3            Japan                 93.77
4          Germany                 94.91
5   United Kingdom                 97.22
6           France                 94.98
7            Italy                 92.62
8           Canada                 94.72
9        Australia                 93.43
10          Brazil                 85.15
11          Russia                 85.65
12     South Korea                 96.56
13           Spain                 94.11
14          Mexico                 79.11
15       Indonesia                 77.51
16    Saudi Arabia                 97.66
17          Turkey                 81.81
18    South Africa                 72.50
19       Argentina                 90.72
20     Netherlands                 97.47
21     Switzerland                 98.21
22          Sweden                 97.55
23          Norway                 97.76
24       Singapore                 95.72

In [238]:
final_merge.sort_values(by='gdp_per_capita', ascending=False).head(5)

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
23,Norway,5421241,580000,5300000,100.0,97.76,0.11
24,Singapore,5850342,530000,5600000,97.5,95.72,0.09
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
9,Australia,25687041,1880000,24000000,99.0,93.43,0.07

In [239]:
total_population = final_merge['population'].sum()
total_population

np.int64(4720039725)

In [240]:
average_internet_penetration = final_merge['internet_penetration'].mean()
average_internet_penetration

np.float64(89.6596)

In [241]:
highest_internet_country = final_merge.loc[final_merge['internet_users'].idxmax(), ['country', 'internet_users']]
highest_internet_country

country                China
internet_users    1080000000
Name: 1, dtype: object

In [242]:
correlation_metric = final_merge['literacy_rate'].corr(final_merge['internet_penetration'])
correlation_metric

np.float64(0.77279756813985)

In [243]:
conn = sqlite3.connect('country_statistics.db')
cursor = conn.cursor()

In [244]:
q1 = "SELECT country, GDP FROM country_statistics ORDER BY GDP DESC LIMIT 5;"
cursor.execute(q1)
for row in cursor.fetchall():
    print(row)

('United States', 30500000)
('China', 19230000)
('Germany', 4744000)
('India', 4187000)
('Japan', 4180000)

In [245]:
q2 = "SELECT AVG(literacy_rate) FROM country_statistics;"
cursor.execute(q2)
print(f"Average Literacy Rate: {cursor.fetchone()[0]:.3f}%")

Average Literacy Rate: 97.248%

In [246]:
q3 = "SELECT country, literacy_rate FROM country_statistics WHERE literacy_rate > 90;"
cursor.execute(q3)
for row in cursor.fetchall():
    print(row)

('United States', 99.0)
('China', 97.2)
('Japan', 99.0)
('Germany', 99.0)
('United Kingdom', 99.0)
('France', 99.0)
('Italy', 99.0)
('Canada', 99.0)
('Australia', 99.0)
('Brazil', 93.2)
('Russia', 99.7)
('South Korea', 98.8)
('Spain', 98.6)
('Mexico', 95.4)
('Indonesia', 96.0)
('Saudi Arabia', 97.3)
('Turkey', 96.7)
('South Africa', 95.0)
('Argentina', 99.1)
('Netherlands', 99.0)
('Switzerland', 99.0)
('Sweden', 99.0)
('Norway', 100.0)
('Singapore', 97.5)

In [247]:
q5 = "SELECT SUM(population) FROM country_statistics;"
cursor.execute(q5)
print(f"Total Population: {cursor.fetchone()[0]}")

Total Population: 4720039725

In [248]:
q6 = "SELECT country, gdp_per_capita FROM country_statistics ORDER BY gdp_per_capita DESC LIMIT 1;"
cursor.execute(q6)
print(f"Country with Highest GDP per Capita: {cursor.fetchone()}")

Country with Highest GDP per Capita: ('Switzerland', 0.11)

In [249]:
export = pd.read_sql_query("SELECT * FROM country_statistics;", conn)
export.to_csv('final_country_statistics.csv', index=False)
print("\n17. Final dataset successfully exported to 'final_country_statistics.csv'")

17. Final dataset successfully exported to 'final_country_statistics.csv'

In [250]:
q8 = "SELECT country, gdp_per_capita FROM country_statistics ORDER BY gdp_per_capita DESC LIMIT 10;"
cursor.execute(q8)
print("Top 10 Countries by GDP per Capita:")
for row in cursor.fetchall():
    print(row)

Top 10 Countries by GDP per Capita:
('Switzerland', 0.11)
('Norway', 0.11)
('United States', 0.09)
('Singapore', 0.09)
('Australia', 0.07)
('Netherlands', 0.07)
('Germany', 0.06)
('United Kingdom', 0.06)
('Canada', 0.06)
('Sweden', 0.06)

In [251]:
cursor.close()
conn.close()

In [252]:
import pandas as pd
import sqlite3

def extract_data():
    """Extracts data from various sources."""
    print("Extracting data...")
    population_data = pd.read_csv('/content/population.csv')
    gdp_data = pd.read_excel("/content/gdp.xlsx")
    internet_df = pd.read_json('/content/internet_users.json')
    literacy_df = pd.read_xml('/content/literacy_rate.xml')
    print("Data extracted successfully.")
    return population_data, gdp_data, internet_df, literacy_df

population_data, gdp_data, internet_df, literacy_df = extract_data()

Extracting data...
Data extracted successfully.

In [253]:
def transform_data(population_data, gdp_data, internet_df, literacy_df):
    """Cleans, renames, merges, and creates new features."""
    print("Transforming data...")

    gdp_data.rename(columns={gdp_data.columns[0]:'country'},inplace=True)
    literacy_df.rename(columns={literacy_df.columns[0]:'country'},inplace=True)

    population_data['population'] = pd.to_numeric(population_data['population'], errors='coerce')
    gdp_data['GDP'] = pd.to_numeric(gdp_data['GDP'], errors='coerce')
    internet_df['internet_users'] = pd.to_numeric(internet_df['internet_users'] ,errors='coerce')
    literacy_df['literacy_rate'] = pd.to_numeric(literacy_df['literacy_rate'], errors='coerce')

    population_data['country'] = population_data['country'].astype(str)
    gdp_data['country'] = gdp_data['country'].astype(str)
    internet_df['country'] = internet_df['country'].astype(str)
    literacy_df['country'] = literacy_df['country'].astype(str)

    merged_1 = pd.merge(population_data, gdp_data, on='country', how='inner')
    merged_2 = pd.merge(merged_1, internet_df, on='country', how='inner')
    final_merge = pd.merge(merged_2, literacy_df, on='country', how='inner')

    final_merge['internet_penetration'] = (final_merge['internet_users'] / final_merge['population']) * 100
    final_merge['internet_penetration'] = final_merge['internet_penetration'].round(2)
    final_merge['gdp_per_capita'] = final_merge['GDP'] / final_merge['population']
    final_merge['gdp_per_capita'] = final_merge['gdp_per_capita'].round(2)

    print("Data transformed successfully.")
    return final_merge

final_merge = transform_data(population_data, gdp_data, internet_df, literacy_df)
display(final_merge.head())

Transforming data...
Data transformed successfully.

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

In [254]:
def load_data(final_merge, db_name='country_statistics.db', csv_name='final_country_statistics_etl.csv'):
    print(f"Loading data to {db_name} and {csv_name}...")

    conn = sqlite3.connect(db_name)
    final_merge.to_sql('country_statistics', conn, if_exists='replace', index=False)
    conn.close()

    final_merge.to_csv(csv_name, index=False)

    print("Data loaded successfully.")


load_data(final_merge)

Loading data to country_statistics.db and final_country_statistics_etl.csv...
Data loaded successfully.

In [255]:
conn = sqlite3.connect('country_statistics.db')
verification_df = pd.read_sql_query("SELECT * FROM country_statistics LIMIT 5;", conn)
display(verification_df)
conn.close()
print("Data verified in SQLite.")

,country,population,GDP,internet_users,literacy_rate,internet_penetration,gdp_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

Data verified in SQLite.

Write a short summary (5–6 points) explaining your ETL process, including:

● Data sources used:
read various data sets like csv, excel, json and xml

● Data cleaning steps:
rename,  calculated values
● Transformations performed:

● Database loading process: merged final_merge to sqlite4

● Key insights obtained from the analysis:
sqlite 3